name: grading workflow
on:
  repository_dispatch:
    types: ["bread"]

jobs:
  use-lg:
    runs-on: ubuntu-latest
    steps:
      - name: read payload
                uses: githubtraining/looking-glass-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          feedback: ${{ steps.events.outputs.reports }}
