name: perform the dispatch
on: workflow_dispatch

jobs:
  send-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: dispatch bitches
        uses: ./.github/actions/local-action
        with:
          repo_token: ${{ secrets.MY_PAT }}
